'use client';

import { useMemo, useState } from 'react';
import { useJobs } from '@/lib/hooks/use-jobs';
import { useArtifacts } from '@/lib/hooks/use-artifacts';
import { Spinner } from '@/components/ui/spinner';
import { ErrorState } from '@/components/ui/error-state';
import { EmptyState } from '@/components/ui/empty-state';

export function ArtifactsView() {
  const jobsState = useJobs({});
  const [jobId, setJobId] = useState<string>('');

  const defaultJobId = useMemo(() => jobId || jobsState.jobs[0]?.id || '', [jobId, jobsState.jobs]);

  const artifacts = useArtifacts(defaultJobId);

  return (
    <div className="flex flex-1 flex-col gap-4 p-6">
      <div>
        <h1 className="text-base font-semibold text-zinc-100">Artifacts</h1>
        <p className="mt-1 text-xs text-zinc-500">Browse workspace files generated by jobs.</p>
      </div>

      <div className="max-w-xl">
        <label className="mb-1 block text-xs text-zinc-500">Job</label>
        <select
          value={defaultJobId}
          onChange={(e) => setJobId(e.target.value)}
          className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm text-zinc-100"
        >
          {jobsState.jobs.map((job) => (
            <option key={job.id} value={job.id}>
              {job.title} ({job.id})
            </option>
          ))}
        </select>
      </div>

      {!defaultJobId ? (
        <EmptyState title="No jobs" description="Create a job first to view artifacts." />
      ) : artifacts.loading ? (
        <div className="flex justify-center py-12">
          <Spinner size="lg" />
        </div>
      ) : artifacts.error ? (
        <ErrorState message={artifacts.error} onRetry={artifacts.refetch} />
      ) : artifacts.items.length === 0 ? (
        <EmptyState
          title="No artifacts found"
          description="This workspace path currently has no files."
        />
      ) : (
        <div className="overflow-hidden rounded-xl border border-zinc-800">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-zinc-800 bg-zinc-900">
                <th className="px-4 py-2 text-left text-zinc-500">Name</th>
                <th className="px-4 py-2 text-left text-zinc-500">Path</th>
                <th className="px-4 py-2 text-left text-zinc-500">Type</th>
                <th className="px-4 py-2 text-left text-zinc-500">Size</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-800/60">
              {artifacts.items.map((item) => (
                <tr key={item.id} className="bg-zinc-900/40">
                  <td className="px-4 py-2 text-zinc-200">{item.name}</td>
                  <td className="px-4 py-2 font-mono text-zinc-500">{item.path}</td>
                  <td className="px-4 py-2 text-zinc-400">
                    {item.is_directory ? 'directory' : item.source}
                  </td>
                  <td className="px-4 py-2 text-zinc-400">
                    {item.is_directory ? '—' : item.size_bytes.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
