'use client';

import { useMemo, useState } from 'react';
import { useJobs } from '@/lib/hooks/use-jobs';
import { useArtifacts } from '@/lib/hooks/use-artifacts';
import { Badge } from '@/components/ui/badge';
import { Spinner } from '@/components/ui/spinner';
import { ErrorState } from '@/components/ui/error-state';
import { EmptyState } from '@/components/ui/empty-state';

export function ArtifactsView() {
  const jobsState = useJobs({});
  const [jobId, setJobId] = useState<string>('');

  const defaultJobId = useMemo(() => jobId || jobsState.jobs[0]?.id || '', [jobId, jobsState.jobs]);

  const artifacts = useArtifacts(defaultJobId);

  return (
    <div className="flex flex-1 flex-col gap-4">
      <section className="console-surface-strong console-hairline overflow-hidden rounded-xl px-5 py-5">
        <div className="space-y-3">
          <div>
            <p className="console-kicker">Workspace outputs</p>
            <h1 className="mt-2 text-3xl font-semibold text-[color:var(--foreground)]">
              Artifacts
            </h1>
            <p className="mt-2 max-w-2xl text-sm leading-6 text-[color:var(--foreground-soft)]">
              Browse files generated by a selected run without leaving the control room.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Badge variant="default">{jobsState.jobs.length} jobs available</Badge>
            <Badge variant="default">{artifacts.items.length} artifacts loaded</Badge>
          </div>
        </div>
      </section>

      <div className="console-surface rounded-lg p-4">
        <label className="mb-2 block text-xs font-semibold uppercase tracking-[0.12em] text-[color:var(--foreground-soft)]">
          Job
        </label>
        <select
          value={defaultJobId}
          onChange={(e) => setJobId(e.target.value)}
          className="w-full rounded-lg border border-[color:var(--line)] bg-black/15 px-4 py-3 text-sm text-[color:var(--foreground)] outline-none transition focus:border-[color:var(--line-strong)]"
        >
          {jobsState.jobs.map((job) => (
            <option key={job.id} value={job.id}>
              {job.title} ({job.id})
            </option>
          ))}
        </select>
      </div>

      {!defaultJobId ? (
        <EmptyState title="No jobs" description="Create a job first to view artifacts." />
      ) : artifacts.loading ? (
        <div className="flex justify-center py-12">
          <Spinner size="lg" />
        </div>
      ) : artifacts.error ? (
        <ErrorState message={artifacts.error} onRetry={artifacts.refetch} />
      ) : artifacts.items.length === 0 ? (
        <EmptyState
          title="No artifacts found"
          description="This workspace path currently has no files."
        />
      ) : (
        <div className="console-surface overflow-hidden rounded-xl">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-[color:var(--line)] bg-black/5 text-left text-[color:var(--foreground-muted)]">
                <th className="px-5 py-3">Name</th>
                <th className="px-5 py-3">Path</th>
                <th className="px-5 py-3">Type</th>
                <th className="px-5 py-3">Size</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[color:var(--line)]">
              {artifacts.items.map((item) => (
                <tr key={item.id} className="bg-black/5 hover:bg-white/[0.03]">
                  <td className="px-5 py-4 text-[color:var(--foreground)]">{item.name}</td>
                  <td className="px-5 py-4 font-mono text-xs text-[color:var(--foreground-muted)]">
                    {item.path}
                  </td>
                  <td className="px-5 py-4 text-[color:var(--foreground-soft)]">
                    {item.is_directory ? 'directory' : item.source}
                  </td>
                  <td className="px-5 py-4 text-[color:var(--foreground-soft)]">
                    {item.is_directory ? '—' : item.size_bytes.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
